services:
  - type: web
    name: mumblr-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
